import type { Metadata } from "next";
import { Barlow, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { twMerge } from 'tailwind-merge';

const barlow = Barlow({variable: "--font-barlow", weight: ['100', '200', '300'], subsets: ['latin']})
const barlow_Condensed = Barlow_Condensed({variable: "--font-barlow", weight: ['100', '200', '300'], subsets: ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(`${barlow.variable} ${barlow_Condensed.variable} antialiased`)}
      >
       <Providers>{children}</Providers>
      </body>
    </html>
  );
}
